name: Daily Dev Joke

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: Update Daily Joke
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update README with daily joke
        uses: ahmadreza-log/daily-dev-jokes@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "🤣 Update Daily Joke"
          COMMIT_USERNAME: "ahmadreza-log"
          COMMIT_EMAIL: ${{ secrets.EMAIL }}
          LABEL: "joke"
          START_MARKER: "<!--START_SECTION:dev-jokes-->"
          END_MARKER: "<!--END_SECTION:dev-jokes-->"
          README_PATH: "README.md"
